=== USDepartmentofLabor/UICliamantIntake/schemas/identity-v1.0.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://unemployment.dol.gov/schemas/identity-v1.0.json",
  "title": "UI Claimant Identity",
  "description": "Unemployment Insurance claimant identity",
  "type": "object",
  "additionalProperties": false,
  "definitions": {
    "email": {
      "$id": "/definitions/email",
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "description": "Email address verified via identity_provider",
      "type": "string",
      "format": "email",
      "maxLength": 128,
      "comment": "Note that JSON Schema validation of email format is notoriously loose but identity providers confirm the email address itself so we trust only what we get from them"
    }
  },
  "required": [
    "email",
    "id",
    "claimant_id",
    "identity_provider",
    "identity_assurance_level",
    "swa_code"
  ],
  "properties": {
    "id": {
      "description": "Unique identifier",
      "type": "string",
      "format": "uuid"
    },
    "claimant_id": {
      "description": "Identifier for the Claimant. Unique to the Identity Provider used.",
      "type": "string"
    },
    "swa_xid": {
      "description": "Cross-reference ID provided by the SWA at the time of requesting Identity check",
      "type": "string"
    },
    "identity_provider": {
      "description": "Name of the Identity Provider used to authenticate the Claimant",
      "type": "string"
    },
    "identity_assurance_level": {
      "description": "https://pages.nist.gov/800-63-3-Implementation-Resources/63A/ial2remote/",
      "type": "integer",
      "enum": [1, 2]
    },
    "swa_code": {
      "description": "2-letter code identifying the State Workforce Agency",
      "type": "string"
    },
    "validated_at": {
      "description": "Datetime of the last time the Claim was validated against this schema",
      "type": "string",
      "format": "date-time"
    },
    "$schema": {
      "description": "URL of this schema",
      "type": "string"
    },
    "birthdate": {
      "description": "Date of birth",
      "type": "string",
      "format": "date"
    },
    "phone": {
      "description": "Verified phone number",
      "type": "string"
    },
    "ssn": {
      "description": "Social Security Number",
      "type": "string",
      "pattern": "^[0-9]{3}-[0-9]{2}-[0-9]{4}$"
    },
    "verified_at": {
      "description": "Date of IAL2 verification, when known",
      "type": "string",
      "format": "date-time"
    },
    "first_name": {
      "description": "Given name",
      "type": "string"
    },
    "last_name": {
      "description": "Family name",
      "type": "string"
    },
    "address": {
      "description": "Verified address",
      "type": "object",
      "properties": {
        "address1": { "type": "string", "maxLength": 64 },
        "address2": { "type": "string", "maxLength": 64 },
        "city": { "type": "string", "maxLength": 64 },
        "state": { "type": "string", "maxLength": 2, "minLength": 2 },
        "zipcode": {
          "type": "string",
          "maxLength": 12,
          "pattern": "^\\d{5}(-\\d{4})?$"
        }
      },
      "required": ["address1", "city", "state", "zipcode"]
    },
    "email": {
      "description": "Verified via identity_provider",
      "$ref": "#/definitions/email"
    },
    "all_emails": {
      "type": "array",
      "items": { "$ref": "#/definitions/email" }
    }
  }
}

=== USDepartmentofLabor/UICliamantIntake/schemas/identity-v1.0-example-ial2.json
{
  "$schema": "https://unemployment.dol.gov/schemas/identity-v1.0.json",
  "id": "19c05261-db64-4c78-ad54-4e1a75fdc508",
  "swa_xid": "35188697-18d5-44c0-bc59-0347930095c9",
  "claimant_id": "opaque-claimaint-string",
  "identity_provider": "login.gov",
  "identity_assurance_level": 2,
  "validated_at": "2022-02-26T14:47:02-06:00",
  "swa_code": "XX",
  "email": "someone@example.com",
  "all_emails": ["someone@example.net"],
  "birthdate": "2000-01-01",
  "ssn": "900-00-1234",
  "address": {
    "address1": "123 Any St",
    "city": "Somewhere",
    "state": "KS",
    "zipcode": "00000"
  },
  "phone": "555-555-1234",
  "verified_at": "2022-02-03T09:06:36-06:00"
}

=== USDepartmentofLabor/UICliamantIntake/schemas/identity-v1.0-example-ial2-charset.json
{
  "$schema": "https://unemployment.dol.gov/schemas/identity-v1.0.json",
  "id": "29e05261-db64-4c78-ad54-4e1a75fdc508",
  "swa_xid": "34288697-18d5-44c0-bc59-0347930095c9",
  "claimant_id": "opaque-claimaint-string1",
  "identity_provider": "login.gov",
  "identity_assurance_level": 2,
  "validated_at": "2022-02-28T13:44:02-06:00",
  "swa_code": "XX",
  "email": "someone@example.com",
  "all_emails": ["someone@example.net"],
  "first_name": "Jesús",
  "last_name": "Peña",
  "birthdate": "2000-02-02",
  "ssn": "900-00-4567",
  "address": {
    "address1": "879 Pérez St",
    "city": "Somewhere",
    "state": "AR",
    "zipcode": "72200"
  },
  "phone": "555-555-5309",
  "verified_at": "2022-02-04T12:06:36-06:00"
}
